spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
  datasource:
    url:
  h2:
    console:
      enabled: true

openai:
  api:
    key:
    url:
  model:
